SELECT
?id
(REPLACE(STR(?id), "http://www.wikidata.org/entity/", "wikidata:") AS ?qid)
(GROUP_CONCAT(DISTINCT ?alias; SEPARATOR=" <|> ") AS ?aliases)
(GROUP_CONCAT(DISTINCT CONCAT(?conf, " || ", ?confl, " || ", ?confd, " || ", ?confq); SEPARATOR=" <|> ") AS ?contains_formulation)
(GROUP_CONCAT(DISTINCT CONCAT(?quan, " || ", ?quanl, " || ", ?quand, " || ", ?quanq); SEPARATOR=" <|> ") AS ?contains_quantity)
(GROUP_CONCAT(DISTINCT CONCAT(?pub, " || ", ?publ, " || ", ?pubd); SEPARATOR=" <|> ") AS ?publication)

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id skos:altLabel ?alias .
        FILTER (LANG(?alias) = "en")
    }}

    OPTIONAL {{
        ?id p:P4330 ?statement.
        ?statement ps:P4330 ?confraw.
        BIND(REPLACE(STR(?confraw), "http://www.wikidata.org/entity/", "wikidata:") AS ?conf)

        ?confraw wdt:P31 wd:Q976981.

        OPTIONAL {{
            ?confraw rdfs:label ?conflraw.
            FILTER (lang(?conflraw) = 'en')
        }}
        BIND(COALESCE(?conflraw, "No Label Provided!") AS ?confl)

        OPTIONAL {{
            ?confraw schema:description ?confdraw
            FILTER (lang(?confdraw) = 'en')
        }}
        BIND(COALESCE(?confdraw, "No Description Provided!") AS ?confd)

        OPTIONAL {{
            ?statement pq:P3831 ?quaraw.
            BIND(REPLACE(STR(?quaraw), "http://www.wikidata.org/entity/", "wikidata:") AS ?qua)
        }}
        BIND(COALESCE(?qua, "") AS ?confq)
    }}

    OPTIONAL {{
        ?id p:P4330 ?statement2.
        ?statement2 ps:P4330 ?quanraw.

        {{
            ?quanraw wdt:P31 wd:Q309314.
        }}
        UNION
        {{
            ?quanraw wdt:P31 wd:Q110653654.
        }}

        BIND(REPLACE(STR(?quanraw), "http://www.wikidata.org/entity/", "wikidata:") AS ?quan)

        OPTIONAL {{
            ?quanraw rdfs:label ?quanlraw.
            FILTER (lang(?quanlraw) = 'en')
        }}
        BIND(COALESCE(?quanlraw, "No Label Provided!") AS ?quanl)

        OPTIONAL {{
            ?quanraw schema:description ?quandraw
            FILTER (lang(?quandraw) = 'en')
        }}
        BIND(COALESCE(?quandraw, "No Description Provided!") AS ?quand)

        OPTIONAL {{
            ?statement2 pq:P3831 ?qua2raw.
            BIND(REPLACE(STR(?qua2raw), "http://www.wikidata.org/entity/", "wikidata:") AS ?qua2)
        }}
        BIND(COALESCE(?qua2, "") AS ?quanq)
    }}

    OPTIONAL {{
        ?id p:P1343 ?statement_p .
        ?statement_p ps:P1343 ?pubraw .
        ?statement_p pq:P3831 ?role .
        VALUES ?role {{ wd:Q788790 wd:Q12579633 wd:Q265158 wd:Q1298668 wd:Q1724915 }}
        BIND(REPLACE(STR(?pubraw), "http://www.wikidata.org/entity/", "wikidata:") AS ?pub)

        OPTIONAL {{
            ?pubraw rdfs:label ?publraw.
            FILTER (lang(?publraw) = 'en')
        }}
        BIND(COALESCE(?publraw, "No Label Provided!") AS ?publ)

        OPTIONAL {{
            ?pubraw schema:description ?pubdraw
            FILTER (lang(?pubdraw) = 'en')
        }}
        BIND(COALESCE(?pubdraw, "No Description Provided!") AS ?pubd)
    }}
}}
GROUP BY ?id