'''Main export entry points and RDMO provider classes for MaRDMO.

Provides:

- :class:`BaseMaRDMOExportProvider` — abstract base for all MaRDMO export
  providers; extends :class:`~MaRDMO.oauth2.OauthProviderMixin` with
  catalog-specific submission, preview, and export logic.
- :class:`MaRDMOExportProvider` — concrete RDMO export provider registered
  in ``apps.py``; handles form rendering, catalog dispatch, and background
  job scheduling.
- :class:`ExportForm` — minimal Django form used on the export action page.
- Four ``submit_mardmo_*`` methods implementing catalog-specific export flows
  for model, algorithm, workflow, and search catalogs.
'''

import logging
from abc import ABC

from django import forms
from django.conf import settings
from django.http import HttpRequest
from django.shortcuts import redirect, render, reverse
from django.utils.translation import gettext_lazy as _

from rdmo.projects.exports import Export
from rdmo.services.providers import OauthProviderMixin

from .checks import Checks
from .getters import (
    get_answers,
    get_item_url,
    get_options,
    get_questions,
    get_url
)
from .helpers import  (
    compare_items,
    inline_mathml,
    is_cyclic,
    process_question_dict,
    topological_order
)
from .oauth2 import OauthProviderMixin
from .views import render_preview

from .model.worker import PrepareModel

from .algorithm.worker import PrepareAlgorithm

from .workflow.utils import get_discipline
from .workflow.worker import prepareWorkflow
from .search.worker import search
from .publication.worker import PublicationRetriever

logger = logging.getLogger(__name__)

class BaseMaRDMOExportProvider(OauthProviderMixin, Export, ABC):
    '''Base export provider wiring MaRDMO to the MaRDI Portal OAuth2 flow.

    Provides the concrete MaRDI Portal URLs and credentials needed by
    :class:`~MaRDMO.oauth2.OauthProviderMixin`.  Subclasses implement
    the catalog-specific :meth:`render` and :meth:`submit_*` methods.
    '''
    @property
    def oauth2_client_id(self):
        '''OAuth2 client ID read from ``settings.MARDMO_PROVIDER["mardi"]``.'''
        return settings.MARDMO_PROVIDER['mardi']['oauth2_client_id']

    @property
    def oauth2_client_secret(self):
        '''OAuth2 client secret read from ``settings.MARDMO_PROVIDER["mardi"]``.'''
        return settings.MARDMO_PROVIDER['mardi']['oauth2_client_secret']

    @property
    def authorize_url(self):
        '''MaRDI Portal OAuth2 authorization endpoint URL.'''
        return f"{get_url('mardi', 'uri')}/w/rest.php/oauth2/authorize"

    @property
    def token_url(self):
        '''MaRDI Portal OAuth2 token exchange endpoint URL.'''
        return f"{get_url('mardi', 'uri')}/w/rest.php/oauth2/access_token"

    @property
    def redirect_path(self):
        '''Callback path registered with the MaRDI Portal OAuth2 application.'''
        return reverse('oauth_callback', args=['wikibase'])

    def get_authorize_params(self, request, state):
        '''Return OAuth2 authorization query parameters for the MaRDI Portal.

        Args:
            request: Django HTTP request (unused — client ID is from settings).
            state:   CSRF state token generated by the OAuth2 flow.

        Returns:
            Dict with ``response_type``, ``client_id``, and ``state`` keys.
        '''
        return {
            'response_type': 'code',
            'client_id': self.oauth2_client_id,
            'state': state
        }

    def get_callback_data(self, request):
        '''Return POST body fields for the MaRDI Portal token exchange request.

        Args:
            request: Django HTTP request supplying the ``code`` GET parameter.

        Returns:
            Dict with ``client_id``, ``client_secret``, ``grant_type``, and
            ``code`` fields.
        '''
        return {
            'client_id': self.oauth2_client_id,
            'client_secret': self.oauth2_client_secret,
            'grant_type': 'authorization_code',
            'code': request.GET.get('code')
        }

class MaRDMOExportProvider(BaseMaRDMOExportProvider):
    """Handles MaRDMO export logic.

    Attributes:
        request: The Django HttpRequest associated with the provider.
    """

    request: HttpRequest

    class ExportForm(forms.Form):
        '''Empty form class required by the RDMO Export provider interface.'''

    def render(self):
        '''Render the catalog-appropriate preview or documentation page.

        Dispatches to the correct preview/submit method based on the active
        catalog (model, algorithm, workflow, or search).

        Returns:
            HTTP response rendering the preview page or an error page for
            unknown catalogs.
        '''
        # MaRDMO: Mathematical Model Documentation
        if str(self.project.catalog).endswith(
            (
                'mardmo-model-catalog',
                'mardmo-model-basics-catalog'
            )
        ):

            # Get answers, options, and mathmoddb
            answers, options = self.get_post_data('preview')

            # Select Template
            if str(self.project.catalog).endswith('mardmo-model-basics-catalog'):
                template = 'MaRDMO/modelTemplate-basics.html'
            else:
                template = 'MaRDMO/modelTemplate.html'

            return render_preview(
                self = self,
                template = template,
                answers = answers,
                option = options
            )

        # MaRDMO: Algorithm Documentation
        if str(self.project.catalog).endswith('mardmo-algorithm-catalog'):

            # Get answers, options, mathalgodb
            answers, options = self.get_post_data('preview')

            return render_preview(
                self = self,
                template = 'MaRDMO/algorithmTemplate.html',
                answers = answers,
                option = options
            )

        # MaRDMO: Search Interdisciplinary Workflows, Mathematical Models or Algorithms
        if str(self.project.catalog).endswith('mardmo-search-catalog'):

            answers, options = self.get_post_data('preview')

            return render_preview(
                self = self,
                template = 'MaRDMO/serachTemplate.html',
                answers = answers,
                option = options
            )

        # MaRDMO: Interdisciplinary Workflow Documentation
        if str(self.project.catalog).endswith('mardmo-interdisciplinary-workflow-catalog'):

            answers, options = self.get_post_data('preview')

            # Get Model Data
            prepare = prepareWorkflow()
            answers = prepare.preview(answers)

            # Adjust MathML for Preview
            inline_mathml(answers)

            return render_preview(
                self = self,
                template = 'MaRDMO/workflowTemplate.html',
                answers = answers,
                option = options
            )

        # Non-MaRDMO Catalog
        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Catalog Error'),
                'errors': [_('The catalog is not supported by the MaRDMO Plugin.')]
            },
            status=200
        )

    def submit(self):
        """Dispatch the form submission to the catalog-appropriate handler.

        Handles the cancel action (redirects to the project page for all
        catalogs), then routes to :meth:`submit_mardmo_model`,
        :meth:`submit_mardmo_algorithm`, :meth:`submit_mardmo_search`, or
        :meth:`submit_mardmo_workflow` based on the active project catalog.

        Returns:
            HTTP redirect or rendered response from the selected submit method.
        """

        # Handle cancel for all submissions
        if 'cancel' in self.request.POST:
            return redirect('project', self.project.id)

        catalog = str(self.project.catalog)

        if catalog.endswith(('mardmo-model-catalog', 'mardmo-model-basics-catalog')):
            return self.submit_mardmo_model()
        if catalog.endswith('mardmo-algorithm-catalog'):
            return self.submit_mardmo_algorithm()
        if catalog.endswith('mardmo-search-catalog'):
            return self.submit_mardmo_search()
        if catalog.endswith('mardmo-interdisciplinary-workflow-catalog'):
            return self.submit_mardmo_workflow()

        # Default fallback if catalog type is unknown
        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Unknown catalog'),
                'errors': [_('Cannot handle this catalog type.')]
            },
            status=400
        )

    def submit_mardmo_model(self):
        '''Validate and submit the Mathematical Model documentation to the MaRDI Portal.

        Checks OAuth2 credentials, runs all model-catalog consistency checks,
        assembles the Wikibase payload (items + relations), and delegates to
        :meth:`~.oauth2.OauthProviderMixin.post` for the authenticated upload.

        Returns:
            HTTP response — either an error page (missing credentials or failed
            checks) or a redirect to the OAuth authorization flow.
        '''

        # Check MaRDI Portal Credentials
        if not (self.oauth2_client_id and self.oauth2_client_secret):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Missing Credentials'),
                    'errors': [_('Credentials for MaRDI Portal are missing!')]
                },
                status=200
            )

        answers, __ = self.get_post_data()

        # Validate documentation completeness / consistency
        checker = Checks()

        err = checker.run_model(
            project = self.project,
            data = answers,
            catalog = str(self.project.catalog)
        )

        if err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _("Incomplete or Inconsistent Documentation"),
                    'errors': err
                },
                status=200
            )

        # Prepare payload
        try:
            prepare = PrepareModel()
            payload, dependency = prepare.export(
                answers,
                get_url('mardi', 'uri')
            )
        except (ValueError, KeyError) as err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Value Error'),
                    'errors': [err]
                },
                status=200
            )

        # Check if Dependency Graph of Documentation is cyclic
        if is_cyclic(dependency):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Inconsistent Documentation'),
                    'errors': ['Cyclic Dependency Graph']
                },
                status=200
            )

        # Order the creation of Items following their dependencies
        dependency_ordered = topological_order(dependency)

        return self.post(self.request, payload, dependency_ordered)


    def submit_mardmo_algorithm(self):
        '''Validate and submit the Algorithm documentation to the MaRDI Portal.

        Checks OAuth2 credentials, runs all algorithm-catalog consistency checks,
        assembles the Wikibase payload (items + relations), and delegates to
        :meth:`~.oauth2.OauthProviderMixin.post` for the authenticated upload.

        Returns:
            HTTP response — either an error page (missing credentials or failed
            checks) or a redirect to the OAuth authorization flow.
        '''

        # Check MaRDI Portal Credentials
        if not (self.oauth2_client_id and self.oauth2_client_secret):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Missing Credentials'),
                    'errors': [_('Credentials for MaRDI Portal are missing!')]
                },
                status=200
            )

        answers, __ = self.get_post_data()

        # Validate documentation completeness / consistency
        checker = Checks()

        err = checker.run_algorithm(
            project = self.project,
            data = answers
        )

        if err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _("Incomplete or Inconsistent Documentation"),
                    'errors': err
                },
                status=200
            )

        # Prepare payload
        try:
            prepare = PrepareAlgorithm()
            payload, dependency = prepare.export(
                answers,
                get_url('mardi', 'uri')
            )
        except (ValueError, KeyError) as err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Value Error'),
                    'errors': [err]
                },
                status=200
            )

        # Check if Dependency Graph of Documentation is cyclic
        if is_cyclic(dependency):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Inconsistent Documentation'),
                    'errors': ['Cyclic Dependency Graph']
                },
                status=200
            )

        # Order the creation of Items following their dependencies
        dependency_ordered = topological_order(dependency)

        return self.post(self.request, payload, dependency_ordered)

    def submit_mardmo_search(self):
        '''Execute a MaRDI Portal search and return matching results as JSON.

        Reads the search type from the answers dict and dispatches to the
        appropriate search handler (workflow, model, or algorithm).

        Returns:
            :class:`~django.http.JsonResponse` with a ``"links"`` key listing
            matching portal items, or an error JSON on unknown search type.
        '''

        answers, options = self.get_post_data()

        if answers['search']['options'] == options['InterdisciplinaryWorkflow']:
            datatype = "Workflow(s)"
            source = "MaRDI Portal"
        elif answers['search']['options'] == options['MathematicalModel']:
            datatype = "Mathematical Model(s)"
            source = "MathModDB KG"
        elif answers['search']['options'] == options['Algorithm']:
            datatype = "Algorithm(s)"
            source = "MathAlgoDB KG"
        else:
            datatype = "Unknown"
            source = "Unknown"

        return render(
            self.request,
            'MaRDMO/searchResults.html',
            {
                'datatype': datatype,
                'source': source,
                'noResults': answers['no_results'],
                'links': answers['links']
            },
            status=200
        )

    def submit_mardmo_workflow(self):
        '''Prepare and render the Interdisciplinary Workflow documentation preview.

        Checks OAuth2 credentials, assembles the workflow answers into the
        preview/export template context, and renders the result page.

        Returns:
            HTTP response — either an error page (missing credentials) or a
            rendered workflow documentation page.
        '''

        # Check MaRDI Portal Credentials
        if not (self.oauth2_client_id and self.oauth2_client_secret):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Missing Credentials'),
                    'errors': [_('Credentials for MaRDI Portal are missing!')]
                },
                status=200
            )

        answers, __ = self.get_post_data()

        try:
            prepare = prepareWorkflow()
            payload, dependency = prepare.export(
                answers,
                self.project.title,
                get_url('mardi', 'uri')
            )
        except (ValueError, KeyError) as err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Value Error'),
                    'errors': [err]
                },
                status=200
            )

        # Check if Dependency Graph of Documentation is cyclic
        if is_cyclic(dependency):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Inconsistent Documentation'),
                    'errors': ['Cyclic Dependency Graph']
                },
                status=200
            )

        # Order the creation of Items following their dependencies
        dependency_ordered = topological_order(dependency)

        return self.post(self.request, payload, dependency_ordered)

    def post_success(self, request, init, final):
        '''Render the success page listing all newly created MaRDI Portal items.

        Args:
            request: Django HTTP request.
            init:    Deep copy of the original payload dict (before posting).
            final:   Updated payload dict containing assigned Wikibase IDs.

        Returns:
            Rendered ``core/success.html`` response with links to created items.
        '''
        ids = compare_items(init, final)

        # Links to newly created Entities
        return render(
            request,
            'MaRDMO/portalExport.html',
            {
                'ids': ids,
                'mardi_uri': get_item_url('mardi')
            },
            status=200
        )

    def get_post_data(self, mode = 'submit'):
        '''Collect and pre-process user answers for the active catalog.

        Reads all RDMO project values, applies catalog-specific processing
        (relation resolution, publication retrieval, etc.), and returns the
        structured answers dict alongside the global options dict.

        Args:
            mode: ``'preview'`` additionally fetches publication metadata and
                  runs relation resolution for display; ``'submit'`` (default)
                  skips those steps for a leaner export payload.

        Returns:
            Tuple ``(answers, options)`` where *answers* is a nested dict
            organised by entity type (e.g. ``{"field": {...}, "model": {...}}``)
            and *options* maps RDMO option URIs to their string values.
        '''
        options = get_options()

        # MaRDMO: Mathematical Model Documentation
        if str(self.project.catalog).endswith(
            (
                'mardmo-model-catalog',
                'mardmo-model-basics-catalog'
            )
        ):

            # Load Model & Publication Questions
            questions = get_questions('model') | get_questions('publication')

            answers = process_question_dict(
                project = self.project,
                questions = questions,
                get_answer = get_answers
            )

            if mode == 'preview':
                # Retrieve Publications related to Model for Preview
                publication = PublicationRetriever()
                answers = publication.get_information(
                    project = self.project,
                    snapshot = self.snapshot,
                    answers = answers,
                    options = options
                )

            # Prepare Mathematical Model (Preview)
            prepare = PrepareModel()
            answers = prepare.preview(answers)

            return answers, options

        # MaRDMO: Algorithm Documentation
        if str(self.project.catalog).endswith('mardmo-algorithm-catalog'):

            # Load Algorithm and Publication Questions
            questions = get_questions('algorithm') | get_questions('publication')

            answers = process_question_dict(
                project = self.project,
                questions = questions,
                get_answer = get_answers
            )

            if mode == 'preview':
                # Retrieve Publications related to Model for Preview
                publication = PublicationRetriever()
                answers = publication.get_information(
                    project = self.project,
                    snapshot = self.snapshot,
                    answers = answers,
                    options = options
                )

            # Prepare Mathematical Model (Preview)
            prepare = PrepareAlgorithm()
            answers = prepare.preview(answers)

            return answers, options

        # MaRDMO: Search Interdisciplinary Workflow, Mathematical Model or Algorithm
        if str(self.project.catalog).endswith('mardmo-search-catalog'):

            # Load Data for Interdisciplinary Workflow, Mathematical Model or Algorithm Search
            questions = get_questions('search')

            answers = process_question_dict(
                project = self.project,
                questions = questions,
                get_answer = get_answers
            )

            # Get Results from MaRDI Resources
            answers = search(
                answers,
                options
            )

            return answers, options

        # MaRDMO: Interdisciplinary Workflow Documentation
        if str(self.project.catalog).endswith('mardmo-interdisciplinary-workflow-catalog'):

            # Load Interdisciplinary Workflow and Publication Questions
            questions = get_questions('workflow') | get_questions('publication')

            answers = process_question_dict(
                project = self.project,
                questions = questions,
                get_answer = get_answers
            )

            # Refine associated Disciplines
            answers = get_discipline(answers)

            # Retrieve Publications related to Workflow
            publication = PublicationRetriever()
            answers = publication.get_information(
                project = self.project,
                snapshot = self.snapshot,
                answers = answers,
                options = options
            )

            return answers, options

        # Default fallback if catalog type is unknown
        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Unknown catalog'),
                'errors': [_('Cannot handle this catalog type.')]
            },
            status=400
        )
