SELECT DISTINCT
?id
(REPLACE(STR(?id), "http://www.wikidata.org/entity/", "wikidata:") AS ?qid)
?size_value ?size_unit ?size_record ?file_format ?binary_or_text ?proprietary
?DOI ?URL ?publish ?archive ?end_time

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id p:P3575 ?statementNode.
        ?statementNode psv:P3575 ?valueNode.
        ?valueNode wikibase:quantityAmount ?size_value;
                   wikibase:quantityUnit ?unit.
        ?unit rdfs:label ?size_unit.
        FILTER (lang(?size_unit) = 'en')
    }}

    OPTIONAL {{
        ?id wdt:P4876 ?size_record
    }}

    OPTIONAL {{
        ?id wdt:P1195 ?file_format
    }}

    BIND(IF(EXISTS {{ ?id wdt:P31 wd:Q4913888 }}, "binary", IF(EXISTS {{ ?id wdt:P31 wd:Q60476328 }}, "text", "" )) AS ?binary_or_text)

    BIND(IF(EXISTS {{ ?id wdt:P31 wd:Q123684347 }}, "Yes", IF(EXISTS {{ ?id wdt:P31 wd:Q309901 }}, "No", "" )) AS ?proprietary)

    OPTIONAL {{
        ?id wdt:P356 ?DOI.
    }}

    OPTIONAL {{
        ?id wdt:P2699 ?URL.
    }}

    BIND(IF(EXISTS {{ ?id wdt:P4424 wd:Q17051824 }}, "Yes", "No") AS ?publish)

    BIND(IF(EXISTS {{ ?id wdt:P4424 wd:Q17155735 }}, "YesText", "NoText") AS ?archive)

    OPTIONAL {{
        ?id p:P4424 ?statementNode2.
        ?statementNode2 ps:P4424 wd:Q17155735.
        OPTIONAL {{
            ?statementNode2 pq:P582 ?end_time.
        }}
    }}
}}

GROUP BY ?id ?size_value ?size_unit ?size_record ?file_format ?binary_or_text ?proprietary ?DOI ?URL ?publish ?archive ?end_time
