SELECT
?id
(CONCAT("mardi:", STRAFTER(STR(?id), STR(wd:))) AS ?qid)
?number_of_nodes
(GROUP_CONCAT(DISTINCT CONCAT(
    ?cpu_id, " || ", ?cpul, " || ", ?cpud,
    " || ", COALESCE(STR(?cpu_count), "")
); separator=" <|> ") AS ?cpu)
(GROUP_CONCAT(DISTINCT CONCAT(?pub, " || ", ?publ, " || ", ?pubd); separator=" <|> ") AS ?publication)

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id wdt:{number of compute nodes} ?number_of_nodes.
    }}

    OPTIONAL {{
        ?id p:{CPU} ?statement.
        ?statement ps:{CPU} ?cpuraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?cpuraw), STR(wd:))) AS ?cpu_id)

        OPTIONAL {{
            ?cpuraw rdfs:label ?cpulraw
            FILTER (lang(?cpulraw) = 'en')
        }}

        BIND(COALESCE(?cpulraw, "No Label Provided!") AS ?cpul)

        OPTIONAL {{
            ?cpuraw schema:description ?cpudraw
            FILTER (lang(?cpudraw) = 'en')
        }}

        BIND(COALESCE(?cpudraw, "No Description Provided!") AS ?cpud)

        OPTIONAL {{
            ?statement pq:{quantity_property} ?cpu_count.
        }}

    }}

    OPTIONAL {{
        ?id p:{described by source} ?statement_p .
        ?statement_p ps:{described by source} ?pubraw .
        ?statement_p pq:{object has role} ?role .
        VALUES ?role {{ wd:{documentation} wd:{use} }}
        BIND(CONCAT("mardi:", STRAFTER(STR(?pubraw), STR(wd:))) AS ?pub)
        OPTIONAL {{
            ?pubraw rdfs:label ?publraw .
            FILTER (lang(?publraw) = 'en')
        }}
        BIND(COALESCE(?publraw, "No Label Provided!") AS ?publ)
        OPTIONAL {{
            ?pubraw schema:description ?pubdraw .
            FILTER (lang(?pubdraw) = 'en')
        }}
        BIND(COALESCE(?pubdraw, "No Description Provided!") AS ?pubd)
    }}
}}

GROUP BY ?id ?number_of_nodes