SELECT
?id
(REPLACE(STR(?id), "http://www.wikidata.org/entity/", "wikidata:") AS ?qid)
(GROUP_CONCAT(DISTINCT CONCAT(
    ?method, " || ", ?methodl, " || ", ?methodd,
    " || ", COALESCE(?instrument, ""), " || ", COALESCE(?instrumentl, ""), " || ", COALESCE(?instrumentd, ""),
    " || ", COALESCE(?hardware_meth, ""), " || ", COALESCE(?hardwarel_meth, ""), " || ", COALESCE(?hardwared_meth, ""),
    " || ", COALESCE(?doi_method, ""),
    " || ", COALESCE(?url_method, ""),
    " >|< ", COALESCE(?parameters_method, "")
); separator=" <|> ") AS ?uses_method)
(GROUP_CONCAT(DISTINCT CONCAT(
    ?algorithm, " || ", ?algorithml, " || ", ?algorithmd,
    " || ", COALESCE(?software, ""), " || ", COALESCE(?softwarel, ""), " || ", COALESCE(?softwared, ""),
    " || ", COALESCE(?hardware_alg, ""), " || ", COALESCE(?hardwarel_alg, ""), " || ", COALESCE(?hardwared_alg, ""),
    " || ", COALESCE(?doi_algorithm, ""),
    " || ", COALESCE(?url_algorithm, ""),
    " >|< ", COALESCE(?parameters_algorithm, "")
); separator=" <|> ") AS ?uses_algorithm)
(GROUP_CONCAT(DISTINCT CONCAT(?field, " || ", ?fieldl, " || ", ?fieldd); separator=" <|> ") AS ?field_of_work)

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id p:P2283 ?statement_method.
        ?statement_method ps:P2283 ?methodraw.
        FILTER NOT EXISTS {{ ?statement_method pq:P400 ?sw. ?sw wdt:P31 wd:Q7397 }}
        BIND(replace(xsd:string(?methodraw),'http://www.wikidata.org/entity/','wikidata:') as ?method)

        SERVICE wikibase:label {{
            bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
            ?methodraw rdfs:label ?methodlraw .
            ?methodraw schema:description ?methoddraw .
        }}

        BIND(COALESCE(?methodlraw, "No Label Provided!") AS ?methodl)
        BIND(COALESCE(?methoddraw, "No Description Provided!") AS ?methodd)

        OPTIONAL {{
            ?statement_method pq:P400 ?instrumentraw.
            FILTER NOT EXISTS {{ ?instrumentraw wdt:P31 wd:Q17110744 }}
            BIND(replace(xsd:string(?instrumentraw),'http://www.wikidata.org/entity/','wikidata:') as ?instrument)

            SERVICE wikibase:label {{
                bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
                ?instrumentraw rdfs:label ?instrumentlraw .
                ?instrumentraw schema:description ?instrumentdraw .
            }}

            BIND(COALESCE(?instrumentlraw, "No Label Provided!") AS ?instrumentl)
            BIND(COALESCE(?instrumentdraw, "No Description Provided!") AS ?instrumentd)
        }}

        OPTIONAL {{
            ?statement_method pq:P400 ?hw_methraw.
            ?hw_methraw wdt:P31 wd:Q17110744.
            BIND(replace(xsd:string(?hw_methraw),'http://www.wikidata.org/entity/','wikidata:') as ?hardware_meth)

            SERVICE wikibase:label {{
                bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
                ?hw_methraw rdfs:label ?hw_methlraw .
                ?hw_methraw schema:description ?hw_methdraw .
            }}

            BIND(COALESCE(?hw_methlraw, "No Label Provided!") AS ?hardwarel_meth)
            BIND(COALESCE(?hw_methdraw, "No Description Provided!") AS ?hardwared_meth)
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_method (GROUP_CONCAT(?doi_m; SEPARATOR="; ") AS ?doi_method) WHERE {{
                    ?statement_method pq:P356 ?doi_m.
                }}
                GROUP BY ?statement_method
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_method (GROUP_CONCAT(?url_m; SEPARATOR="; ") AS ?url_method) WHERE {{
                    ?statement_method pq:P2699 ?url_m.
                }}
                GROUP BY ?statement_method
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_method (GROUP_CONCAT(?param_method; SEPARATOR=" || ") AS ?parameters_method) WHERE {{
                    ?statement_method pq:P1013 ?param_method.
                }}
                GROUP BY ?statement_method
            }}
        }}
    }}

    OPTIONAL {{
        ?id p:P2283 ?statement_algorithm.
        ?statement_algorithm ps:P2283 ?algorithmraw.
        ?statement_algorithm pq:P400 ?softwareraw.
        ?softwareraw wdt:P31 wd:Q7397.
        BIND(replace(xsd:string(?algorithmraw),'http://www.wikidata.org/entity/','wikidata:') as ?algorithm)

        SERVICE wikibase:label {{
            bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
            ?algorithmraw rdfs:label ?algorithmlraw .
            ?algorithmraw schema:description ?algorithmdraw .
        }}

        BIND(COALESCE(?algorithmlraw, "No Label Provided!") AS ?algorithml)
        BIND(COALESCE(?algorithmdraw, "No Description Provided!") AS ?algorithmd)

        BIND(replace(xsd:string(?softwareraw),'http://www.wikidata.org/entity/','wikidata:') as ?software)

        SERVICE wikibase:label {{
            bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
            ?softwareraw rdfs:label ?softwarelraw .
            ?softwareraw schema:description ?softwaredraw .
        }}

        BIND(COALESCE(?softwarelraw, "No Label Provided!") AS ?softwarel)
        BIND(COALESCE(?softwaredraw, "No Description Provided!") AS ?softwared)

        OPTIONAL {{
            ?statement_algorithm pq:P400 ?hw_algraw.
            ?hw_algraw wdt:P31 wd:Q17110744.
            BIND(replace(xsd:string(?hw_algraw),'http://www.wikidata.org/entity/','wikidata:') as ?hardware_alg)

            SERVICE wikibase:label {{
                bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
                ?hw_algraw rdfs:label ?hw_alglraw .
                ?hw_algraw schema:description ?hw_algdraw .
            }}

            BIND(COALESCE(?hw_alglraw, "No Label Provided!") AS ?hardwarel_alg)
            BIND(COALESCE(?hw_algdraw, "No Description Provided!") AS ?hardwared_alg)
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_algorithm (GROUP_CONCAT(?doi_a; SEPARATOR="; ") AS ?doi_algorithm) WHERE {{
                    ?statement_algorithm pq:P356 ?doi_a.
                }}
                GROUP BY ?statement_algorithm
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_algorithm (GROUP_CONCAT(?url_a; SEPARATOR="; ") AS ?url_algorithm) WHERE {{
                    ?statement_algorithm pq:P2699 ?url_a.
                }}
                GROUP BY ?statement_algorithm
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_algorithm (GROUP_CONCAT(?param_alg; SEPARATOR=" || ") AS ?parameters_algorithm) WHERE {{
                    ?statement_algorithm pq:P1013 ?param_alg.
                }}
                GROUP BY ?statement_algorithm
            }}
        }}
    }}

    OPTIONAL {{
        ?id wdt:P101 ?fieldraw.
        BIND(replace(xsd:string(?fieldraw),'http://www.wikidata.org/entity/','wikidata:') as ?field)

        SERVICE wikibase:label {{
            bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
            ?fieldraw rdfs:label ?fieldlraw .
            ?fieldraw schema:description ?fielddraw .
        }}

        BIND(COALESCE(?fieldlraw, "No Label Provided!") AS ?fieldl)
        BIND(COALESCE(?fielddraw, "No Description Provided!") AS ?fieldd)
    }}

}}

GROUP BY ?id