SELECT DISTINCT
?id
(CONCAT("mardi:", STRAFTER(STR(?id), STR(wd:))) AS ?qid)
(GROUP_CONCAT(DISTINCT CONCAT(?input, " || ", ?inputl, " || ", ?inputd); separator=" <|> ") AS ?input_data_set)
(GROUP_CONCAT(DISTINCT CONCAT(?output, " || ", ?outputl, " || ", ?outputd); separator=" <|> ") AS ?output_data_set)
(GROUP_CONCAT(DISTINCT CONCAT(
    ?method, " || ", ?methodl, " || ", ?methodd,
    " || ", COALESCE(?instrument, ""), " || ", COALESCE(?instrumentl, ""), " || ", COALESCE(?instrumentd, ""),
    " || ", COALESCE(?hardware_meth, ""), " || ", COALESCE(?hardwarel_meth, ""), " || ", COALESCE(?hardwared_meth, ""),
    " || ", COALESCE(?doi_method, ""),
    " || ", COALESCE(?url_method, ""),
    " >|< ", COALESCE(?parameters_method, "")
); separator=" <|> ") AS ?uses_method)
(GROUP_CONCAT(DISTINCT CONCAT(
    ?algorithm, " || ", ?algorithml, " || ", ?algorithmd,
    " || ", COALESCE(?software, ""), " || ", COALESCE(?softwarel, ""), " || ", COALESCE(?softwared, ""),
    " || ", COALESCE(?hardware_alg, ""), " || ", COALESCE(?hardwarel_alg, ""), " || ", COALESCE(?hardwared_alg, ""),
    " || ", COALESCE(?doi_algorithm, ""),
    " || ", COALESCE(?url_algorithm, ""),
    " >|< ", COALESCE(?parameters_algorithm, "")
); separator=" <|> ") AS ?uses_algorithm)
(GROUP_CONCAT(DISTINCT CONCAT(?field, " || ", ?fieldl, " || ", ?fieldd); separator=" <|> ") AS ?field_of_work)

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id wdt:{input data set} ?inputraw
        BIND(CONCAT("mardi:", STRAFTER(STR(?inputraw), STR(wd:))) AS ?input)

        OPTIONAL {{
            ?inputraw rdfs:label ?inputlraw
            FILTER (lang(?inputlraw) = 'en')
        }}

        BIND(COALESCE(?inputlraw, "No Label Provided!") AS ?inputl)

        OPTIONAL {{
            ?inputraw schema:description ?inputdraw
            FILTER (lang(?inputdraw) = 'en')
        }}

        BIND(COALESCE(?inputdraw, "No Description Provided!") AS ?inputd)
    }}

    OPTIONAL {{
        ?id wdt:{output data set} ?outputraw
        BIND(CONCAT("mardi:", STRAFTER(STR(?outputraw), STR(wd:))) AS ?output)

        OPTIONAL {{
            ?outputraw rdfs:label ?outputlraw
            FILTER (lang(?outputlraw) = 'en')
        }}

        BIND(COALESCE(?outputlraw, "No Label Provided!") AS ?outputl)

        OPTIONAL {{
            ?outputraw schema:description ?outputdraw
            FILTER (lang(?outputdraw) = 'en')
        }}

        BIND(COALESCE(?outputdraw, "No Description Provided!") AS ?outputd)
    }}

    OPTIONAL {{
        ?id p:{uses} ?statement_method.
        ?statement_method ps:{uses} ?methodraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?methodraw), STR(wd:))) AS ?method)

        ?methodraw wdt:{instance of} wd:{method}

        OPTIONAL {{
            ?methodraw rdfs:label ?methodlraw
            FILTER (lang(?methodlraw) = 'en')
        }}

        BIND(COALESCE(?methodlraw, "No Label Provided!") AS ?methodl)

        OPTIONAL {{
            ?methodraw schema:description ?methoddraw
            FILTER (lang(?methoddraw) = 'en')
        }}

        BIND(COALESCE(?methoddraw, "No Description Provided!") AS ?methodd)

        OPTIONAL {{
            ?statement_method pq:{platform} ?instrumentraw.
            BIND(CONCAT("mardi:", STRAFTER(STR(?instrumentraw), STR(wd:))) AS ?instrument)

            OPTIONAL {{
                ?instrumentraw rdfs:label ?instrumentlraw
                FILTER (lang(?instrumentlraw) = 'en')
            }}

            BIND(COALESCE(?instrumentlraw, "No Label Provided!") AS ?instrumentl)

            OPTIONAL {{
                ?instrumentraw schema:description ?instrumentdraw
                FILTER (lang(?instrumentdraw) = 'en')
            }}

            BIND(COALESCE(?instrumentdraw, "No Description Provided!") AS ?instrumentd)
        }}

        OPTIONAL {{
            ?statement_method pq:{platform} ?hw_methraw.
            ?hw_methraw wdt:{instance of} wd:{computer hardware}
            BIND(CONCAT("mardi:", STRAFTER(STR(?hw_methraw), STR(wd:))) AS ?hardware_meth)

            OPTIONAL {{
                ?hw_methraw rdfs:label ?hw_methlraw
                FILTER (lang(?hw_methlraw) = 'en')
            }}

            BIND(COALESCE(?hw_methlraw, "No Label Provided!") AS ?hardwarel_meth)

            OPTIONAL {{
                ?hw_methraw schema:description ?hw_methdraw
                FILTER (lang(?hw_methdraw) = 'en')
            }}

            BIND(COALESCE(?hw_methdraw, "No Description Provided!") AS ?hardwared_meth)
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_method (GROUP_CONCAT(?doi_m; SEPARATOR="; ") AS ?doi_method) WHERE {{
                    ?statement_method pq:{DOI} ?doi_m.
                }}
                GROUP BY ?statement_method
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_method (GROUP_CONCAT(?url_m; SEPARATOR="; ") AS ?url_method) WHERE {{
                    ?statement_method pq:{URL} ?url_m.
                }}
                GROUP BY ?statement_method
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_method (GROUP_CONCAT(?param_method; SEPARATOR=" || ") AS ?parameters_method) WHERE {{
                    ?statement_method pq:{comment} ?param_method.
                }}
                GROUP BY ?statement_method
            }}
        }}
    }}

    OPTIONAL {{
        ?id p:{uses} ?statement_algorithm.
        ?statement_algorithm ps:{uses} ?algorithmraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?algorithmraw), STR(wd:))) AS ?algorithm)

        ?algorithmraw wdt:{instance of} wd:{algorithm}

        OPTIONAL {{
            ?algorithmraw rdfs:label ?algorithmlraw
            FILTER (lang(?algorithmlraw) = 'en')
        }}

        BIND(COALESCE(?algorithmlraw, "No Label Provided!") AS ?algorithml)

        OPTIONAL {{
            ?algorithmraw schema:description ?algorithmdraw
            FILTER (lang(?algorithmdraw) = 'en')
        }}

        BIND(COALESCE(?algorithmdraw, "No Description Provided!") AS ?algorithmd)

        OPTIONAL {{
            ?statement_algorithm pq:{platform} ?softwareraw.
            ?softwareraw wdt:{instance of} wd:{software}
            BIND(CONCAT("mardi:", STRAFTER(STR(?softwareraw), STR(wd:))) AS ?software)

            OPTIONAL {{
                ?softwareraw rdfs:label ?softwarelraw
                FILTER (lang(?softwarelraw) = 'en')
            }}

            BIND(COALESCE(?softwarelraw, "No Label Provided!") AS ?softwarel)

            OPTIONAL {{
                ?softwareraw schema:description ?softwaredraw
                FILTER (lang(?softwaredraw) = 'en')
            }}

            BIND(COALESCE(?softwaredraw, "No Description Provided!") AS ?softwared)
        }}

        OPTIONAL {{
            ?statement_algorithm pq:{platform} ?hw_algraw.
            ?hw_algraw wdt:{instance of} wd:{computer hardware}
            BIND(CONCAT("mardi:", STRAFTER(STR(?hw_algraw), STR(wd:))) AS ?hardware_alg)

            OPTIONAL {{
                ?hw_algraw rdfs:label ?hw_alglraw
                FILTER (lang(?hw_alglraw) = 'en')
            }}

            BIND(COALESCE(?hw_alglraw, "No Label Provided!") AS ?hardwarel_alg)

            OPTIONAL {{
                ?hw_algraw schema:description ?hw_algdraw
                FILTER (lang(?hw_algdraw) = 'en')
            }}

            BIND(COALESCE(?hw_algdraw, "No Description Provided!") AS ?hardwared_alg)
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_algorithm (GROUP_CONCAT(?doi_a; SEPARATOR="; ") AS ?doi_algorithm) WHERE {{
                    ?statement_algorithm pq:{DOI} ?doi_a.
                }}
                GROUP BY ?statement_algorithm
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_algorithm (GROUP_CONCAT(?url_a; SEPARATOR="; ") AS ?url_algorithm) WHERE {{
                    ?statement_algorithm pq:{URL} ?url_a.
                }}
                GROUP BY ?statement_algorithm
            }}
        }}

        OPTIONAL {{
            {{
                SELECT ?statement_algorithm (GROUP_CONCAT(?param_alg; SEPARATOR=" || ") AS ?parameters_algorithm) WHERE {{
                    ?statement_algorithm pq:{comment} ?param_alg.
                }}
                GROUP BY ?statement_algorithm
            }}
        }}
    }}

    OPTIONAL {{
        ?id wdt:{field of work} ?fieldraw.

        BIND(CONCAT("mardi:", STRAFTER(STR(?fieldraw), STR(wd:))) AS ?field)

        OPTIONAL {{
            ?fieldraw rdfs:label ?fieldlraw
            FILTER (lang(?fieldlraw) = 'en')
        }}

        BIND(COALESCE(?fieldlraw, "No Label Provided!") AS ?fieldl)

        OPTIONAL {{
            ?fieldraw schema:description ?fielddraw
            FILTER (lang(?fielddraw) = 'en')
        }}

        BIND(COALESCE(?fielddraw, "No Description Provided!") AS ?fieldd)
    }}

}}

GROUP BY ?id